#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Create tmp directory
  win_file: path=C:\temp state=present state=directory

- name: Get SQL Express 2008r2 SP2
  get_url: url=http://download.microsoft.com/download/0/4/B/04BE03CD-EAF3-4797-9D8D-2E08E316C998/SQLEXPR_x64_ENU.exe dest=C:/temp/SQLEXPR_x64_ENU.exe

- name: Upload SQL Configuration
  win_copy: src={{ script_dir }} dest=C:/temp/

- name: Set execution policy
  script: 'Powershell -command `"& {Set-ExecutionPolicy bypass}`"' -scripttype bat

- name: Run prerequisites automation script
  script: "{{ script_dir }}/AutomationScript62.ps1" {{ win_vra_vcaciaasvm }}\Adminsitrator

- name: Configure SQL
  script: 'c:\temp\SQLEXPR_x64_ENU.exe /iacceptSQLServerLicenseTerms /configurationfile=`"c:\temp\SQLConfiguration.ini`"' -wait -scripttype bat

- name: Install SQL
  script: "{{ script_dir }}/StartSQL.ps1" -verb RunAs -scripttype bat

- name: Run vRA script
  script: "{{ script_dir }}/vRA62Automation_v1.ps1"
  register: s_test

- name: Checking for SQL Services
  script: "{{ script_dir }}/SQLCHECK.ps1" "{{ win_vra_vcaciaasvm }}"

- name: Setting and restarting services
  script: "set-service -name SQLBrowser -startuptype Automatic; net start SQLBrowser; restart-Service 'MSSQL*SQLEXPRESS' -Force;restart-Service 'SQLWRITER' -Force"

- name: Adding License key
  script: "/usr/sbin/vcac-config -v license-update --key {{ win_vra_lickey }}"

- name: Getting vCAC Appliance Cert for IAAS
  script: "{{ scritp_dir }}/get-websitecert.ps1" "{{ win_vra_vcacapvm }}.{{ win_vra_dns_sufix }}"

- name: Running vCAC Installation
  script: "{{ script_dir }}/InstallScript.bat" -scripttype bat

